name: Build Nugets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.402 
    - name: Install dependencies
      run: msbuild /t:Restore /p:Configuration=Release AVR8Sharp.sln
    - name: Build
      run: dotnet build -c Release AVR8Sharp/AVR8Sharp.csproj
    - name: Test
      run: dotnet test -c Release Avr8SharpTests/Avr8SharpTests.csproj
    - name: Package Library
      run: |
        mkdir PackageOut
        cd AVR8Sharp && dotnet pack --include-symbols --no-build -c Release -v normal -o ../PackageOut

